import = [
  # git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true
opacity = 1.0
decorations = "None"

[font]
size = 16.0
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

